version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: your-sql-server-container
    environment:
      SA_PASSWORD: YourPassword123!  # Set a strong password for the SA user
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - ./sql-server-data:/var/opt/mssql  # Mount a local directory to persist SQL Server data
